### ISSUE TITLE
矩阵套矩阵不清楚什么情况，比如A，B两个矩阵，A（B）的结果很迷

### ISSUE THREAD

**Issue by 1952061** [RayCorleone/Matlab_Trans_Python#11]

**Comment by RayCorleone** [comment]
![image](https://user-images.githubusercontent.com/65175529/88878166-e2f74680-d259-11ea-9a76-bf8ab4360df5.png)

**Comment by RayCorleone** [comment]
结果是个：按照x中数字取每行中的第一个元素
![image](https://user-images.githubusercontent.com/65175529/88878218-04583280-d25a-11ea-80df-7544fbcbd105.png)
